const countryCityData: Record<string, string[]> = {
    Albania: ["Durrës", "Vlorë", "Shëngjin", "Sarandë"],
    Algeria: ["Algiers", "Oran", "Annaba", "Skikda"],
    Angola: ["Luanda", "Lobito", "Namibe"],
    Argentina: ["Buenos Aires", "Rosario", "Bahía Blanca", "Mar del Plata"],
    Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
    Bangladesh: ["Chittagong", "Mongla"],
    Belgium: ["Antwerp", "Bruges", "Ghent", "Brussels", "Ostend"],
    Brazil: ["Santos", "Rio de Janeiro", "Paranaguá", "Salvador", "Recife"],
    Bulgaria: ["Varna", "Burgas", "Ruse"],
    Cambodia: ["Sihanoukville", "Phnom Penh"],
    Cameroon: ["Douala", "Kribi"],
    Canada: ["Vancouver", "Montreal", "Halifax", "Toronto"],
    Chile: ["Valparaíso", "San Antonio", "Talcahuano"],
    China: ["Shanghai", "Shenzhen", "Guangzhou", "Ningbo", "Qingdao"],
    Colombia: ["Cartagena", "Barranquilla", "Buenaventura"],
    Croatia: ["Rijeka", "Split", "Ploče"],
    Cyprus: ["Limassol", "Larnaca"],
    Denmark: ["Copenhagen", "Aarhus", "Esbjerg"],
    Djibouti: ["Djibouti"],
    "Dominican Republic": ["Santo Domingo", "Puerto Plata", "La Romana", "Haina"],
    Ecuador: ["Guayaquil", "Manta"],
    Egypt: ["Alexandria", "Port Said", "Suez"],
    Estonia: ["Tallinn", "Muuga"],
    Finland: ["Helsinki", "Turku"],
    France: ["Marseille", "Le Havre", "Bordeaux", "Nantes", "Dunkirk"],
    Germany: ["Hamburg", "Bremen", "Bremerhaven", "Lübeck", "Kiel", "Rostock"],
    Ghana: ["Tema", "Takoradi"],
    Greece: ["Piraeus", "Thessaloniki", "Heraklion"],
    Guatemala: ["Puerto Quetzal", "Santo Tomás de Castilla"],
    Honduras: ["Puerto Cortés", "La Ceiba"],
    "Hong Kong": ["Hong Kong"],
    India: ["Mumbai", "Chennai", "Kolkata", "Cochin"],
    Indonesia: ["Jakarta", "Surabaya", "Semarang", "Belawan"],
    Iran: ["Bandar Abbas", "Bandar Imam Khomeini"],
    Iraq: ["Umm Qasr", "Basra"],
    Ireland: ["Dublin", "Cork"],
    Israel: ["Haifa", "Ashdod", "Eilat"],
    Italy: ["Genoa", "Naples", "Venice", "Trieste"],
    "Ivory Coast": ["Abidjan", "San Pedro"],
    Jamaica: ["Kingston", "Montego Bay"],
    Japan: ["Tokyo", "Yokohama", "Osaka", "Kobe", "Nagoya"],
    Jordan: ["Aqaba"],
    Kenya: ["Mombasa"],
    Kuwait: ["Shuwaikh", "Shuaiba"],
    Latvia: ["Riga", "Ventspils"],
    Lebanon: ["Beirut", "Tripoli"],
    Lithuania: ["Klaipeda"],
    Malaysia: ["Port Klang", "Penang", "Johor Bahru"],
    Malta: ["Valletta"],
    Mauritius: ["Port Louis"],
    Mexico: ["Veracruz", "Manzanillo", "Lázaro Cárdenas"],
    Montenegro: ["Bar"],
    Morocco: ["Casablanca", "Tangier", "Agadir"],
    Mozambique: ["Maputo", "Beira"],
    Myanmar: ["Yangon"],
    Namibia: ["Walvis Bay"],
    Netherlands: ["Rotterdam", "Amsterdam", "The Hague", "Utrecht"],
    "New Zealand": ["Auckland", "Wellington", "Christchurch", "Tauranga"],
    Nigeria: ["Lagos", "Port Harcourt", "Apapa"],
    Norway: ["Oslo", "Bergen"],
    Oman: ["Sohar", "Salalah"],
    Pakistan: ["Karachi", "Port Qasim"],
    Panama: ["Balboa", "Colón"],
    Peru: ["Callao", "Paita"],
    Philippines: ["Manila", "Cebu"],
    Poland: ["Gdansk", "Gdynia", "Szczecin"],
    Portugal: ["Lisbon", "Porto", "Sines"],
    Qatar: ["Doha"],
    Romania: ["Constanta"],
    Russia: ["Saint Petersburg", "Vladivostok", "Novorossiysk"],
    "Saudi Arabia": ["Jeddah", "Dammam", "Jubail", "Yanbu"],
    Senegal: ["Dakar"],
    Singapore: ["Singapore"],
    Slovenia: ["Koper"],
    "South Africa": ["Durban", "Cape Town", "Port Elizabeth", "Johannesburg"],
    "South Korea": ["Busan", "Incheon", "Ulsan", "Gwangyang"],
    Spain: ["Barcelona", "Valencia", "Bilbao", "Malaga", "Algeciras"],
    "Sri Lanka": ["Colombo", "Galle", "Trincomalee"],
    Sweden: ["Gothenburg", "Stockholm"],
    Taiwan: ["Kaohsiung", "Keelung"],
    Tanzania: ["Dar es Salaam", "Zanzibar"],
    Thailand: ["Bangkok", "Laem Chabang"],
    "Trinidad and Tobago": ["Port of Spain", "Point Lisas", "Scarborough"],
    Tunisia: ["Tunis", "Sfax"],
    Turkey: ["Istanbul", "Izmir", "Mersin"],
    Ukraine: ["Odessa", "Mariupol"],
    "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Fujairah"],
    "United Kingdom": ["London", "Liverpool", "Southampton", "Bristol", "Manchester"],
    "United States": ["Los Angeles", "New York", "Houston", "Miami", "San Francisco"],
    Uruguay: ["Montevideo", "Nueva Palmira"],
    Venezuela: ["Puerto Cabello", "La Guaira"],
    Vietnam: ["Ho Chi Minh City", "Hai Phong", "Da Nang"],
    Yemen: ["Aden", "Al Hudaydah", "Mukalla"]
};

export default countryCityData;
